image: node:10

cache:
  paths:
    - node_modules/

variables:
  NUXT_MODE: generate

install:
  stage: build
  script:
    - yarn install --frozen-lockfile

lint:
  stage: test
  script:
    - yarn lint

audit:
  stage: test
  script:
    - yarn audit

pages:
  stage: deploy
  script:
    - bash script/build.sh
    - bash script/deploy.sh
  artifacts:
    paths:
      - public
  only:
    - master
