image: node:10

before_script:
  - yarn install --frozen-lockfile

cache:
  paths:
    - node_modules/

pages:
  script:
    - yarn lint
    - yarn generate
  artifacts:
    paths:
      - public
  only:
    - master

