language: node_js

sudo: false

cache:
  yarn: true
  directories:
  - node_modules

node_js:
- '10'

script:
- yarn generate
- yarn lint

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/2019
  keep-history: true
  on:
    branch: master
